### ISSUE TITLE
 Game Crashes with DXGI_ERROR_ACCESS_DENIED After MessageBox Confirmation

### ISSUE THREAD

**Issue by wul7chaos** [mateeeeeee/DirectHook#1] opened 2024-11-25 07:29 UTC
### Description:
I am utilizing the DirectHook project to inject a DLL into *S.T.A.L.K.E.R. 2 - Heart of Chornobyl* with the aim of hooking into its D3D12 rendering pipeline. I have compiled the D3D12HOOK sample provided in the Samples directory and successfully injected the resultant DLL into the game.

After injection, the hook is apparently activated, as evidenced by the message box "Called MyDraw!" that pops up from the `MyDraw` function defined in `dllmain.cpp`. However, upon dismissing the message box by clicking "OK," the game encounters a critical error and crashes, displaying the following message:
![屏幕截图 2024-11-25 145609](https://github.com/user-attachments/assets/2a888848-54d0-4134-a36c-97ea928aab13)

```
LowLevelFatalError [File:D:\STALKER2\s2editor\Engine\Source\Runtime\D3D12RHI\Private\D3D12Util.cpp] [Line: 880]
CurrentQueue.Device->GetDevice()->GetDeviceRemovedReason() failed at 
D:\STALKER2\s2editor\Engine\Source\Runtime\D3D12RHI\Private\D3D12Submission.cpp:910 
with error DXGI_ERROR_ACCESS_DENIED
```

The call stack indicates that the crash originates from `Stalker2_Win64_Shipping`, with the top two entries being `kernel32` and `ntdll`.

### Relevant Code:
The issue arises within the `MyDraw` function in `dllmain.cpp`.

### Steps to Reproduce:
1. Compile the D3D12HOOK sample project from the DirectHook repository.
2. Allow the game to compile the shaders and load the main game interface.
3. Inject the compiled DLL into *S.T.A.L.K.E.R. 2 - Heart of Chornobyl*.
4. Start the game and wait for the message box to appear.
5. Dismiss the message box by clicking "OK".
![屏幕截图 2024-11-25 145443](https://github.com/user-attachments/assets/8cb9b797-ac54-4d19-b9af-468130d012ae)

### Expected Behavior:
The game should continue running smoothly after the hook is executed and the message box is dismissed.

### Actual Behavior:
The game crashes immediately after the message box is dismissed, presenting the aforementioned error.

### Environment:
- **Operating System:** Windows 11 24H2
- **Game:** *S.T.A.L.K.E.R. 2 - Heart of Chornobyl*
- **DirectHook Version:** Latest (built on 2024/11/25)
- **Rendering API:** DirectX 12
- **Engine:** Unreal Engine 5.1

### Additional Information:
- The game utilizes DirectX 12 for rendering.
- A similar error (0x80070005) has been encountered when attempting to create a swap chain using other DX12 hook projects.

### Possible Causes:
- There might be a timing issue, causing the hook to interfere at an inopportune moment during the rendering process.
- The error may stem from issues with the `CreateSwapChain` function or how the device context is accessed and managed within the hook function.

### Questions:
- Are there known issues with hooking into DirectX 12 games that could lead to this specific error?
- Could the error be related to improper handling of the device context within the hook function?
- What additional debugging steps can be taken to further investigate this issue?

Thank you for your assistance!

**Comment by wul7chaos** [comment] 2024-11-25 07:37
Sorry, I found the reason through Google
[https://www.unknowncheats.me/forum/unreal-engine-4-a/635608-d3d12-hook-crashes-ue5-03-a.html](url)
Bing, I searched N times but couldn't find the reason

**Comment by mateeeeeee** [comment] 2024-11-25 11:03
Thanks for reporting the issue. I don't have a UE5 game to test it right now, but I commited a potential fix. Would you mind trying it out?

**Comment by wul7chaos** [comment] 2024-11-25 11:20
Thank you for the update, but the game still crashed.
-------------------------------------------------------------------------------------------------------
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000300000030

D3D12Hook!MyPresent() Samples\D3D12Hook\dllmain.cpp:195
![屏幕截图 2024-11-25 192000](https://github.com/user-attachments/assets/eeadf087-8a2c-4b72-b289-9ba3d639bb9f)

amd_fidelityfx_dx12
amd_fidelityfx_dx12
Stalker2_Win64_Shipping
Stalker2_Win64_Shipping
Stalker2_Win64_Shipping
Stalker2_Win64_Shipping
Stalker2_Win64_Shipping
Stalker2_Win64_Shipping
Stalker2_Win64_Shipping
Stalker2_Win64_Shipping
Stalker2_Win64_Shipping
kernel32
ntdll

**Comment by mateeeeeee** [comment] 2024-11-25 11:55
Ok thanks, I will check in more detail later. In the meantime, could you run D3D12 App from the project and check if it's working? It might be that the queue offset changed in between our win 11 versions (I am using 168 for Windows 11 which works for me but maybe it's not working for your version).  Are you able to put breakpoint and confirm that when reading address 0x0000000300000030 it because of the CommandQueue?

**Comment by wul7chaos** [comment] 2024-11-25 12:45
I added a few lines of code, this is the result of the run, this may not explain the instructions ....
CommandQueue and CommandList do not report errors.
![屏幕截图 2024-11-25 204125](https://github.com/user-attachments/assets/8e2be37a-fcd1-420f-bc79-1778bfc61e09)
D3D12APP is running fine, even after I injected the dll into it, I got the message E_FAIL.
![屏幕截图 2024-11-25 204151](https://github.com/user-attachments/assets/fa603e75-74b4-4a58-a8f6-b066283e3654)
![屏幕截图 2024-11-25 204253](https://github.com/user-attachments/assets/35c02200-b463-46b5-8838-892313c4f51f)

**Comment by mateeeeeee** [comment] 2024-11-25 12:59
Currently the d3d12 app is loading dll itself, you dont need to inject anything. You should see imgui demo window. If not something is wrong. I expect that command queue is not null, but rather some invalid pointer address, caused by using the wrong offset.

EDIT:
The first fail for closing command list is because when initalizing context we close it, so in the first frame we get double close which will cause it to return fail. All others are because you return -1 so you never get to reset the command list.

**Comment by mateeeeeee** [comment] 2024-11-26 00:16
After updating my Windows to 24H2 I was able to reproduce the same crash in my sample app. The issue was, as I suspected, the new offset of command queue in swapchain pointer (now 0x138 instead of 0x168). Could you try again now?

**Comment by wul7chaos** [comment] 2024-11-26 01:09
Thank you very much for the update, the program is now working correctly on Windows24H2!
![屏幕截图 2024-11-26 090731](https://github.com/user-attachments/assets/8e1df344-0211-418b-8ab1-ef0ac741c375)

**Closed as completed** 2024-11-26 03:21 UTC
